#!/bin/sh
firefox_profile_dir=${HOME}/.mozilla/firefox
if [ ! -O "${firefox_profile_dir}/profiles.ini" ]
then
mkdir -p ${firefox_profile_dir}/6pwi1bhh.default

echo 'user_pref("gfx.webrender.all", true);' > ${firefox_profile_dir}/6pwi1bhh.default/user.js

cat > "${firefox_profile_dir}/profiles.ini" <<EOF
[Profile0]
Name=default
IsRelative=1
Path=6pwi1bhh.default
Default=1

[General]
StartWithLastProfile=1
Version=2
EOF
fi
