#!/bin/sh

real_wayland=$(dirname "$XDG_RUNTIME_DIR")/${WAYLAND_DISPLAY:-wayland-0}

if [ -O "${real_wayland}" ] && [ snapctl is-connected wayland ]
then
  mkdir -p ${XDG_RUNTIME_DIR}
  ln -sf "${real_wayland}" "$XDG_RUNTIME_DIR"
  export MIR_SERVER_WAYLAND_HOST=${WAYLAND_DISPLAY:-wayland-0}
  unset WAYLAND_DISPLAY
fi
