name: egmde-confined-desktop
version: egmde
version-script: |
  LANG=C apt-cache policy libmircore1 | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/'$(git --git-dir=parts/egmde/src/.git rev-list --count HEAD)'-mir\1/p'
summary: A minimal Mir based desktop with some test applications
description: A minimal Mir based desktop with some test applications for demonstration purposes.
confinement: strict
grade: devel
base: core18

apps:
  egmde-confined-desktop:
    command: bin/run-egmde
    daemon: simple
    slots:
      - mir
      - wayland
    plugs:
      - opengl
      - pulseaudio
    environment:
      EGMDE_FONT:         $SNAP/usr/share/fonts/truetype/freefont/FreeSansBold.ttf
      EGMDE_DESKTOP_PATH: $SNAP/usr/share/applications
      SHELL: bash
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
      PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
      XCURSOR_PATH:    $SNAP/icons
      # XDG config
      XDG_RUNTIME_DIR: $SNAP_DATA/.xdg_runtime_dir
      XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
      XDG_CONFIG_HOME: $SNAP_DATA/.config
      XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
      XDG_DATA_DIRS: ${SNAP}/usr/share:$XDG_DATA_DIRS
      XDG_DATA_HOME: ${SNAP}/usr/share
      # Prep for Mir
      MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      # Prep EGL
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      # Prep for Qt wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/
      QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/platforms/
      QTCHOOSER_NO_GLOBAL_DIR: 1
      QT_SELECT: snappy-qt5
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
      # Needed for fontconfig
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
      # GL Config
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      # Alsa config
      ALSA_CONFIG_DIR: $SNAP/usr/share/alsa
      ALSA_CONFIG_PATH: ${SNAP}/usr/share/alsa
      ALSA_MIXER_SIMPLE: ${SNAP}/usr/share/alsa
      # Lua config
      LUA_PATH: ${SNAP}/usr/share/games/caveexpress/
      # neverball
      NEVERBALL_DATA: $SNAP/usr/share/games/neverball/

parts:
  ppa-mir-release:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:mir-team/release
      # We shouldn't need to install stuff here, but it seems to fix intermittent build failures
      sudo apt --assume-yes install libmiral-dev mir-graphics-drivers-desktop
      sudo apt clean
      snapcraftctl pull

  egmde:
    after: [ppa-mir-release]
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
    - pkg-config
    - libmiral-dev
    - libboost-filesystem-dev
    - libfreetype6-dev
    - libwayland-dev
    - libxkbcommon-dev
    stage-packages:
    - fonts-freefont-ttf
    - mir-graphics-drivers-desktop
    - libmiral3

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default
    prime:
     - icons/default

  glue:
    plugin: dump
    source: glue

  misc:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    - libxcb1
    - libpulse0
    - libsndfile1
    - libasyncns0
    - liblua5.2-0
    - libslang2
    - libglu1-mesa
    - libgpm2
    - libgtk3-nocsd0
    - dbus
    # Debugging
    - gdb
    - strace

  sd2-apps:
    plugin: nil
    stage-packages:
    - libsdl2-2.0-0
    - libsdl2-image-2.0-0
    - libsdl2-mixer-2.0-0
    - libsdl2-net-2.0-0
    # SDL2 games
    - neverball
    - neverputt
#    - caveexpress  ** hardcodes Lua path to /usr/share/games/caveexpress/
#    - 0ad          ** Causes snap build to fail

  qt-apps:
    plugin: nil
    stage-packages:
    # Wayland platform
    - qtwayland5
    - libqt5core5a
    - libqt5dbus5
    - libqt5gui5
    - libqt5widgets5
    - libqt5x11extras5
    - libqtermwidget5-0
    # Apps
    - stellarium
    - qterminal
    - qtcreator
    - wireshark
    - quiterss
#    - kolourpaint    ** Pulls in kio, which adds ktelnetservice5.desktop (which fails to launch without URL)
#    - qutebrowser    ** built for X11 only
#    - falkon         ** built for X11 only
#    - vlc-plugin-qt  **Hard coded path to vlc
#    - vlc

#  gtk3-apps:
# I've given up trying to include GTK+ apps. There are a number
# of configuration options to sort out for the non-desktop,
# confined environment.
# I found that dbus-run-session fails inside a confined snap,
# and they all try to talk to dbus.
# One day, there will be a good way to launch apps and they won't
# need to be wrapped into this snap.
#    plugin: nil
#    stage-packages:
#    - gnome-mahjongg
#    - gnome-chess
#    - gnuchess
#    - gnuchess-book
#    - aisleriot
#    - gnome-cards-data
#    - libxkbcommon0
#    - ttf-ubuntu-font-family
#    - dmz-cursor-theme
#    - light-themes
#    - adwaita-icon-theme
#    - gnome-themes-standard
#    - shared-mime-info
#    - libgtk-3-0
#    - libgtk2.0-0
#    - libgdk-pixbuf2.0-0
#    - libglib2.0-bin
#    - libgtk-3-bin
#    - unity-gtk3-module
#    - libappindicator3-1
#    - locales-all
#    - xdg-user-dirs
#    - ibus-gtk3
#    - libibus-1.0-5

#  native-apps:
#    plugin: nil
#    stage-packages:
#    - glmark2-es2-wayland ** Hard coded path to data