#!/bin/sh
set -e

# we install with the daemon disabled, the configure hook
# will start and enable it if appropriate
snapctl stop --disable $SNAP_NAME.daemon

# GDK pixbuf setup
# For unknown reasons LD_LIBRARY_PATH is just "${SNAP}/graphics/lib" when the hook executes
LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:${SNAP}/graphics/lib:${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/lib/${ARCH_TRIPLET}:${SNAP}/usr/lib/${ARCH_TRIPLET}
$SNAP/usr/lib/${ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > "$GDK_PIXBUF_MODULE_FILE"